{
  "formatVersion": "1.1",
  "component": {
    "group": "xh.zero.core",
    "module": "core",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "wdkpjlhqebhwjhptpcshydtfye"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-1.0.2.aar",
          "url": "core-1.0.2.aar",
          "size": 82110,
          "sha512": "fde547db97e5ad75638c9998f1a7641c02df918e9f86dbe5e1765ac9f0e4599be45fa986f60006898e9e357201bb406e33c571e86afc866967ccb325125afed4",
          "sha256": "9664c1165ce869899d0213aa51aa034ecb874f34b703d67043c7c0623049c376",
          "sha1": "04b88caf4dc4ceb9fec07e0b519e0ad60732d751",
          "md5": "9cf4cc5e81603639203491234b100c72"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.2.aar",
          "url": "core-1.0.2.aar",
          "size": 82110,
          "sha512": "fde547db97e5ad75638c9998f1a7641c02df918e9f86dbe5e1765ac9f0e4599be45fa986f60006898e9e357201bb406e33c571e86afc866967ccb325125afed4",
          "sha256": "9664c1165ce869899d0213aa51aa034ecb874f34b703d67043c7c0623049c376",
          "sha1": "04b88caf4dc4ceb9fec07e0b519e0ad60732d751",
          "md5": "9cf4cc5e81603639203491234b100c72"
        }
      ]
    }
  ]
}
